/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Taxonomic Expert is a person who is an expert in the field of taxonomy, the science of defining and naming groups of biological organisms on the basis of shared characteristics.
 */
export interface TaxonomicExpert {
  /**
   * The unique identifier of the Taxonomic Expert object
   */
  "@id": string;
  /**
   * The type of the object, in this case TaxonomicExpert
   */
  "@type"?: "TaxonomicExpert";
  /**
   * The name of the Taxonomic Expert
   */
  name?: string;
  /**
   * The email of the Taxonomic Expert
   */
  email?: string;
  /**
   * A short description of the Taxonomic Expert
   */
  topDescription?: string;
  /**
   * Languages the user is proficient or fluent in.
   */
  languages?: (
    | "English (EN)"
    | "French (FR)"
    | "Dutch (NL)"
    | "German (DE)"
    | "Spanish (ES)"
    | "Italian (IT)"
    | "Portuguese (PT)"
    | "Polish (PL)"
    | "Swedish (SV)"
    | "Czech (CS)"
    | "Hungarian (HU)"
    | "Romanian (RO)"
    | "Greek (EL)"
    | "Bulgarian (BG)"
    | "Slovak (SK)"
    | "Finnish (FI)"
    | "Danish (DA)"
    | "Lithuanian (LT)"
    | "Latvian (LV)"
    | "Estonian (ET)"
    | "Slovenian (SL)"
    | "Croatian (HR)"
    | "Maltese (MT)"
    | "Irish (GA)"
  )[];
  [k: string]: unknown;
}
