/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generic concept of a Service or Tool
 */
export interface TaxonomicService {
  /**
   * The unique identifier of the Taxonomic Service object
   */
  "@id": string;
  /**
   * The type of the object, in this case taxonomicService
   */
  "@type": "taxonomicService";
  /**
   * The timestamp that the object version was created
   */
  "cetaf:created"?: string;
  /**
   * Modification date for Taxonomic Service information
   */
  "dcterms:modified": string;
  /**
   * The current state of the object
   */
  "cetaf:state": string;
  /**
   * A type that defines the kind of taxonomic service
   */
  "cetaf:taxonomicServiceType":
    | "AITrainingDataset"
    | "communityGroup"
    | "crowdSourcing"
    | "dataTool"
    | "e-LearningService"
    | "factsheet"
    | "identification"
    | "inventory"
    | "referenceCollection"
    | "specimenDatasetNotInGBIF"
    | "website";
  /**
   * http://purl.org/dc/terms/licence
   */
  "dcterms:licence": string;
  /**
   * Brief and descriptive name of the Resource as assigned by the Provider
   */
  "erp:name": string;
  /**
   * A high-level description in fairly non-technical terms of a) what the Resource does, functionality it provides and Resources it enables to access, b) the benefit to a user/customer delivered by a Resource; benefits are usually related to alleviating pains (e.g., eliminate undesired outcomes, obstacles or risks) or producing gains (e.g. increased performance, social gains, positive emotions or cost saving), c) list of customers, communities, users, etc. using the Resource.
   */
  "erp:description": string;
  /**
   * Short catchphrase for marketing and advertising purposes. It will be usually displayed close to the Resource name and should refer to the main value or purpose of the Resource.
   */
  "erp:tagLine"?: string;
  /**
   * Indicators for the language the service is written in, using ISO alpha-3/ISO 639-2
   */
  "erp:languageAvailabilities": string[];
  /**
   * Link to the logo/visual identity of the Resource. The logo will be visible at the Portal. If there is no specific logo for the Resource the logo of the Provider may be used.
   */
  "erp:logo"?: string;
  /**
   * A named group of Resources that offer access to the same type of Resources.
   */
  "erp:category": string;
  /**
   * A persistent identifier, a unique reference to the (Multi-Provider Regional or Thematic) Catalogue in the context of the EOSC Portal.
   */
  "erp:EOSC_serviceId"?: string;
  /**
   * Version of the Resource that is in force in EOSC.
   */
  "erp:version"?: string;
  /**
   * Date of the latest update of the Resource in EOSC.
   */
  "erp:lastUpdate"?: string;
  /**
   * The taxonomic scope on which the service acts upon, e.g. the taxonomic level (genus, species, etc.)
   */
  "cetaf:taxonomicScope"?: string[];
  /**
   * A quality indicator for the purpose of the service
   */
  "cetaf:qualityScore": number;
  /**
   * Comments that describes the admin review and why a certain state is given
   */
  "cetaf:reviewComment"?: string;
  /**
   * Email to contact your helpdesk, where users with incidents and requests will be directed.
   */
  "erp:helpdeskEmail"?: string;
  /**
   * Link to the helpdesk where users with incidents and requests will be directed. It should allow private communication with providers (not a public forum). Create a dedicated URL for your Resources and provide the shortest possible alias.
   */
  "erp:helpdeskPage"?: string;
  /**
   * Contains zero or more cetaf:Agent objects
   */
  "cetaf:hasAgent": Agent[];
  /**
   * Webpage with information about the Resource usually hosted and maintained by the Provider.
   */
  "erp:webpage"?: string;
  /**
   * Link to the documentation of the service
   */
  "cetaf:documentationUrl"?: string;
  /**
   * Webpage with the supported payment models and restrictions that apply to the Resource.
   */
  "erp:paymentModel": string;
  /**
   * Link describing the rules, resource conditions and usage policy which one must agree to abide by in order to use the Resource. Create a dedicated URL for your Resources and provide the shortest possible alias.
   */
  "erp:termsOfUse"?: string;
  /**
   * Name of the funding program that supported the development and/or operation of the Resource.
   */
  "erp:fundingProgram"?: string;
  /**
   * Object representing the service's software
   */
  "cetaf:Software"?: {
    /**
     * Link pointing to the source URL of the software, e.g. the GitHub repository
     */
    "cetaf:sourceUrl": string;
    /**
     * List any other EOSC Resources that your Resource requires in order to operate.
     */
    "erp:requiredResources"?: string[];
    /**
     * Boolean indicating if the software has been deprecated
     */
    "cetaf:deprecated"?: boolean;
    /**
     * Summary of the Resource features updated from the previous version.
     */
    "erp:changeLog"?: string;
    /**
     * List of programming lanugages used in the software
     */
    "cetaf:programmingLanguages"?: string[];
    [k: string]: unknown;
  };
  /**
   * Array of multimedia objects, pointing to their respective sources
   */
  "cetaf:hasMultimedia"?: {
    /**
     * Link to video, screenshots or slides showing details of the Resource.
     */
    "erp:multimediaUrl": string;
    /**
     * http://purl.org/dc/terms/licence
     */
    "dcterms:licence"?: string;
    [k: string]: unknown;
  }[];
}
export interface Agent {
  /**
   * A unique identifier to identify the agent; ORCID or Wikidata identifiers are valid
   */
  "cetaf:agentId": string;
  /**
   * Full name of the agent
   */
  "cetaf:fullName"?: string;
  /**
   * The role assigned to the agent
   */
  "cetaf:role"?: string;
  [k: string]: unknown;
}
